/****************************/
/* Create Tracker Database  */
/****************************/
-- Description: Create MSSQL Database for tracker data
-- Author:		Jason Buss
-- Created:		2016-03-21
-- Remember to set path!

USE [master]
GO

/****** Object:  Database [FXTracker]    Script Date: 2016-03-21 8:21:32 PM ******/
CREATE DATABASE [FXTracker]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tracker', FILENAME = N'D:\SQL\Data\FXTracker.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Tracker_log', FILENAME = N'D:\SQL\Data\FXTracker_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FXTracker] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FXTracker].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FXTracker] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FXTracker] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FXTracker] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FXTracker] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FXTracker] SET ARITHABORT OFF 
GO

ALTER DATABASE [FXTracker] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FXTracker] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [FXTracker] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FXTracker] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FXTracker] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FXTracker] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FXTracker] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FXTracker] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FXTracker] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FXTracker] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FXTracker] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FXTracker] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FXTracker] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FXTracker] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FXTracker] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FXTracker] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FXTracker] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FXTracker] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FXTracker] SET RECOVERY FULL 
GO

ALTER DATABASE [FXTracker] SET  MULTI_USER 
GO

ALTER DATABASE [FXTracker] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FXTracker] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FXTracker] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FXTracker] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FXTracker] SET  READ_WRITE 
GO